// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormEmployeeController from "./form_employee_controller"
application.register("form-employee", FormEmployeeController)

import IndexEmployeeController from "./index_employee_controller"
application.register("index-employee", IndexEmployeeController)
